apiVersion: v1
kind: Pod
metadata:
  name: chamo-demo-pod
  labels:
    name: webserver
spec:
  containers:
  - name: webserver-00
    image: nginx:latest
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: chamo-demo-pvc
  volumes:
  - name: chamo-demo-pvc
    persistentVolumeClaim:
      claimName: chamo-demo-pvc
      readOnly: false
