---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: chamo-demo-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: default
     name: chamo-demo-pvc
  hostPath:
    path: "/tmp/data"
